site_name: PocketEngine Docs
site_url: https://qiulinfan.github.io/pocketEngine/documentation/
repo_url: https://github.com/qiulinfan/pocketEngine
repo_name: qiulinfan/pocketEngine
docs_dir: docs/lua-api
site_dir: .site/documentation

theme:
  name: mkdocs
  logo: ../icon.png
  favicon: ../icon.png

nav:
  - Documentation Home: index.md
  - Component Model: component-model.md
  - Application, Scene, and Camera: application-scene.md
  - Actor: actor.md
  - Rendering, Audio, and Input: rendering-audio-input.md
  - Events and Physics: events-physics.md
  - Built-in Components: builtin-components.md

markdown_extensions:
  - tables
  - admonition
